### ISSUE TITLE
Dashboard Description and Sketching 

### ISSUE THREAD

**Issue by elina-linglin** [UBC-MDS/dsci-532_group_02#11]
Hi everyone, here is the Google doc link to work on: 

https://docs.google.com/document/d/1DwMWtf9BHZ92dZ-VkzYcku3BM1--xpHLFnO2vjDqarI/edit?usp=sharing

**Comment by elabandari** [comment]
Hi Elina, 

Just to confirm, you are spearheading the design?

Let me know if there is anything I can do to support you.

**Comment by KangboLu** [comment]
We have finalized our design.
