### ISSUE TITLE
Peer Feedback

### ISSUE THREAD

**Issue by tanmaysharma19** [UBC-MDS/dsci-532_group_02#28]
Hey group-2,
Congratulations on completing milestone1! I’m sure Beth would really like your dashboard. Here are a few thoughts from group-1:

**What we really liked:**

- We think you’ve a really novel concept and your pitch is great. The persona fits nicely with your theme and the country-wise trends promote inclusivity.
- We really like the color cards for the different brands. 
- It is also interesting to see the different foundation shades as per best selling brands for different countries.

**Some food for thought:**

- Perhaps you could try using a different color palette for the second chart on the right to keep it distinct from the left chart.
- Maybe you can consider expanding the tool-tip of your right chart to also include the mean/median lightness per each brand.
- If I were Beth, I would like to know how am I performing in comparison to my competitor brands. The stacked historgams are good but maybe another visualization (violin/boxplot/facet) summarizing comparative performance of brands (where the user has the option to select and compare brands through a widget) might help inform Beth if she should be focusing on selling specific shades, how the brands are performing across countries etc.

All the best!

**Comment by elina-linglin** [comment]
Hi Group 1:

Thank you for the detailed feedback! Those are great suggestions that would for sure make our app better.

The idea of having a few more widgets for easier comparison was extensively discussed within the group, and is also something we are interested in implementing for future development of the app.

Feel free to come back and explore any future updates. Good luck with your project! 

Cheers,
Group 2

**Comment by elabandari** [comment]
Hi Group 1, 

Thanks again for the great feedback. 

We have decided to use different colours for the two histograms as per your suggestion.

Best, 
Ela on Behalf of Group2
