### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by ghost** [UBC-MDS/dsci-532_group_02#29]
Hey Group 2, congrats on completing your eponymous milestone! Overall, I think your dashboard looks great. I appreciate the clear intuitive design and the wholly effective use of interactivity. Your reflection was also well thought out and addressed most of the issues I see. That said, I have a few minor points of feedback:
- would be nice to fit this all on one medium sized screen, which I think may be possible in your case
- slider should be set not to highlight everything to the left since you're just selecting X not from 0 to X
- could put brand and product name on separate lines to avoid the line split you get right now with longer names
- slider spacing is broken locally for me, but looks fine on heroku, so ok. (See this mentioned in your reflection too, it is tough)
- white text on purple tooltip would be more legible, but I guess that's plotly default, might be tough to change I'm not sure

Also a few suggestions for potential additional features (that don't require more data), if you have time for them:
- show the score that specifues how similar each of the top 5 colors are to that specified (makes comparisons more objective) 
- set the sliders to the color of one of the listed foundations when it is clicked (Would allow one to answer the question "hey, that shade looks a lot like ours, how similar is it really?" without having to check one's own catalogue)
- ability to choose the X axis variable for the histograms (i.e. to Hue or Saturation) 
- If you change your mind regarding filtering by country/brand, here's a suggestion to address the second issue you mentioned: if nothing is selected you could just have it be the same as having all countries selected

Final note on the README update component:
- Good description of app and useful gifs, but you should also include details for those wishing to develop your app (part 2)

**Comment by elina-linglin** [comment]
Hey Chris @gubbelcn,

Thank you so much for taking the time to provide such detailed feedback on our project! Upon the discussion we had earlier during the lab time, here are some follow-up thoughts on your suggestions:

- The team has reached an agreement to not implement the suggested minor changes to the design, and to preserve the current layout for the time being, considering the limited time available for this short project. Your recommendations regarding design details are mostly related to the default setting of Dash and Plotly, which would be our future interest to experiment on as well.

- We agreed that it would be more objective and convenient for users to compare the matching colours with the specified HSV values by providing certain scores in terms of similarity. However, considering that our target audience are experts in the makeup markets, we expect them to have some knowledge of colours that would allow them to make the comparison by their own standards. 

Again, thank you for contributing your feedback to making our app better!

Best,
Group 2

**Comment by rainbowxyt0305** [comment]
Commented.
