### ISSUE TITLE
Project proposal

### ISSUE THREAD

**Issue by KangboLu** [UBC-MDS/dsci-532_group_02#3]
Reference to the milestone template: https://github.ubc.ca/MDS-2020-21/DSCI_532_viz-2_students/blob/master/release/milestone1/milestone1.md

Briefly explain your idea here for brainstorming:
1. Motivation and purpose:
2. Description of the dataset with the dataset link:
3. Research questions you want to explore:

**Comment by elabandari** [comment]
Hi Team, 

I came across a variety of seemingly interesting datasets and I thought I would share them with you:

**A) Birth control Dataset**

1. Motivation & Purpose: Provide women with a tool where they can explore data surrounding birth control options, their effectiveness and potential side effects so they feel empowered about making decisions about their reproductive health. 
2. Description of the dataset with the dataset link: Comprehensive dataset on birth control usage collected by the pudding -> https://github.com/the-pudding/data/tree/master/birth-control
3. Research questions you want to explore: What is the most popular form of birth control? What birth control has the highest satisfaction rate? What birth control has the mildest side effects?

**B) Halloween Candy** 
1. Motivation and purpose: Given the increasing prevalence of obesity and type II diabetes, we should be conscious of the treats we are giving to our children. Using halloween candy data we can determine which candy bars are popular yet have low sugar content.   
2. Description of the dataset with the dataset link: Dataset includes all popular candy bars with their sugar percentage and a rating of their popularity. Collected by 538. Link here -> https://github.com/fivethirtyeight/data/blob/master/candy-power-ranking/candy-data.csv
3. Research questions you want to explore: What are the top candy bars in the low sugar category? How do their ratings compare to candy bars in the high sugar category? 

**B) Makeup Shades** 
1. Motivation and purpose: Those with darker skin tones often have trouble accessing makeup products that match their skin tone. This is especially an issue in North America where major brands cater their product to those with lighter skin tones.
2. Description of the dataset with the dataset link: Dataset across the globe on shades of foundation offered by popular makeup companies. Collected by the pudding: Link -> https://github.com/the-pudding/data/tree/master/makeup-shades.
3. Research questions you want to explore: Do women with darker skin tones have equal access to makeup products (i.e. foundation) compared to women with lighter skin tones?

**Comment by KangboLu** [comment]
**Idea 1: Vancouver Airbnb Rental Market Dashboard**
**1. Motivation and purpose:**
**Our role**: Data scientist consultancy firm
**Audience**: A group of existing homeowners want to make their homes as Airbnb listing
**Motivation and Purpose**: Many of our clients don't have a good perspective of the Vancouver Airbnb rental market. We provide data analytic solutions for our clients to speed up the market research process with a dashboard of the existing Airbnb rental listing price and the host backgrounds data. With the ability to filter by neighborhood, our dashboard will allow our client to explore the listing profiles such as building type, listing capacity, listing price, listing location with the Airbnb host's profiles such as the number of listings published, response time, response rate, acceptance rate, and is the host a super host, 

**2. Description of the dataset with the dataset link:** [Link to the dataset](http://insideairbnb.com/get-the-data.html)
We will explore the available 2020 Airbnb rental data with 9830 entries.
Available columns below. We can discuss to reduce more columns.
**Host profile columns:**
host_name | host_since | host_response_time | host_response_rate | host_acceptance_rate | host_is_superhost | host_neighbourhood | host_listings_count | host_total_listings_count | host_has_profile_pic | host_identity_verified 
**Property profile columns:**
id | listing_url|neighbourhood_cleansed | latitude | longitude | property_type | room_type | accommodates | bathrooms_text | bedrooms | beds | price | number_of_reviews | first_review | last_review | review_scores_rating | instant_bookable | reviews_per_month

**3. Research questions you want to explore:**
Our clients want to explore how are the competitors on the market are doing in terms of rating, pricing, and what type of building are they renting to the public; and also what do the host profiles look like in Vancouver Airbnb rental market.

---
**Idea 2: World Happiness Study Dashboard**
**1. Motivation and purpose:**
**Our role**: Data scientist consultancy firm
**Audience**: UN Social Scientist
**Motivation and Purpose**: Social scientist wants to study the world happiness. We provide data science product solution to answer the research question of:

1. What countries or regions rank the highest in overall happiness and each of the six factors contributing to happiness? 
2. How did country ranks or scores change from 2015 to 2019?
3. Did any country experience a significant increase or decrease in happiness?

**2. Description of the dataset with the dataset link:** [Link to the dataset](https://www.kaggle.com/unsdsn/world-happiness)
Size about 78.9KB. Easy to work with.
> The World Happiness 2017, which ranks 155 countries by their happiness levels, was released at the United Nations at an event celebrating International Day of Happiness on March 20th. The report continues to gain global recognition as governments, organizations and civil society increasingly use happiness indicators to inform their policy-making decisions. Leading experts across fields – economics, psychology, survey analysis, national statistics, health, public policy and more – describe how measurements of well-being can be used effectively to assess the progress of nations. The reports review the state of happiness in the world today and show how the new science of happiness explains personal and national variations in happiness.
>The happiness scores and rankings use data from the Gallup World Poll. The scores are based on answers to the main life evaluation question asked in the poll. This question, known as the Cantril ladder, asks respondents to think of a ladder with the best possible life for them being a 10 and the worst possible life being a 0 and to rate their own current lives on that scale. The scores are from nationally representative samples for the years 2013-2016 and use the Gallup weights to make the estimates representative. The columns following the happiness score estimate the extent to which each of six factors – economic production, social support, life expectancy, freedom, absence of corruption, and generosity – contribute to making life evaluations higher in each country than they are in Dystopia, a hypothetical country that has values equal to the world’s lowest national averages for each of the six factors. They have no impact on the total score reported for each country, but they do explain why some countries rank higher than others.

**3. Research questions you want to explore:**
1. What countries or regions rank the highest in overall happiness and each of the six factors contributing to happiness? 
2. How did country ranks or scores change from 2015 to 2019?
3. Did any country experience a significant increase or decrease in happiness?

**Comment by rainbowxyt0305** [comment]
Dataset: https://www.kaggle.com/unsdsn/world-happiness?select=2019.csv

Reason for choosing: Very interesting, clean, small, and easy to work with dataset

1. Motivation and purpose:

Policy makers and social scientists want to study the state of happiness of the world, and we can provide a Dashboard product solution to answer the research questions:

> 1. What is the highest ranking country in overall happiness score and how are the 6 contributing factors lead to the overall score?
> 2. How did the overall happiness score change for each country from 2016 to 2017 (most recent available years)?
> 3. Did any country experience a significant increase or decrease in happiness?

2. Description of the dataset

>The happiness scores and rankings use data from the Gallup World Poll. The scores are based on answers to the main life evaluation question asked in the poll. This question, known as the Cantril ladder, asks respondents to think of a ladder with the best possible life for them being a 10 and the worst possible life being a 0 and to rate their own current lives on that scale. The scores are from nationally representative samples for the years 2013-2016 and use the Gallup weights to make the estimates representative. The columns following the happiness score estimate the extent to which each of six factors – economic production, social support, life expectancy, freedom, absence of corruption, and generosity – contribute to making life evaluations higher in each country than they are in Dystopia, a hypothetical country that has values equal to the world’s lowest national averages for each of the six factors. They have no impact on the total score reported for each country, but they do explain why some countries rank higher than others.

3. Research questions you want to explore:

> 1. What is the highest ranking country in overall happiness score and how are the 6 contributing factors lead to the overall score?
> 2. How did the overall happiness score change for each country from 2016 to 2017 (most recent available years)?
> 3. Did any country experience a significant increase or decrease in happiness?
