### ISSUE TITLE
Milestone 4 feedback

### ISSUE THREAD

**Issue by ghost** [UBC-MDS/dsci-532_group_02#38]
Hey Group 2,

Congrats on finishing this project! I think your final product turned out quite well. The new colour schemes are much better (although I might've gone less saturated). These colours also no longer have that tooltip contrast issue, so you've indirectly solved that problem as well, which is nice. In a longer project a few more features could be added, as discussed before, but for this timescale I think the functionality is excellent. I would still have liked to see better spacing with the titles and different text styling to help visually separate different components, but this is a relatively minor point. 

Overall, great job! And best of luck with the rest of your courses!

**Comment by elina-linglin** [comment]
Hi Chris,

Thank you for your help all along! We will keep in mind your suggestions on the spacing and text styles for future exploration of the project. 

Best,
Group 2
