### ISSUE TITLE
Research Questions

### ISSUE THREAD

**Issue by elabandari** [UBC-MDS/dsci-532_group_02#7]
Hi Team, 

Please post your ideas for research questions for the [makeup shades](https://github.com/the-pudding/data/tree/master/makeup-shades) dataset below.

**Comment by elabandari** [comment]
Research question ideas: 

1. What range of foundation shades (measured by lightness values) does each brand offer? 
2. What is the range of foundation shades offered by US, Indian, Japanese and Nigerian best seller products? Which country has the most diverse range of foundation shades?

**Comment by rainbowxyt0305** [comment]
I really like this research idea: `What is the range of foundation shades offered by US, Indian, Japanese and Nigerian best seller products? Which country has the most diverse range of foundation shades?`

As this is overarching enough and can have more implications than focusing on individual H, S, V, L values.

**Comment by KangboLu** [comment]
Some ideas:
1. X = group, Y = shades for studying what are shades available from each group's best-seller product lists. 
   The choice of the chart can be a 2D heatmap.
2. X = group, Y = brand for studying what brands available are for each group's best-seller product lists. 
   The choice of the chart can be a 2D heatmap too since the 2D histogram can summarize a large data in a small space.
3. X = brand, Y = shades for studying the distribution, or the proportion of how the shades are available in the best-seller lists.
   The choice of the chart can be a histogram or bar chart.

**Comment by elina-linglin** [comment]
I came up with a few possible research questions:

1. Is the shade spectrum of a particular brand mainly catering to lighter or darker skin tones?

Although most foundation products in the dataset cover as many shades as 40, the range of the shades on the spectrum is different among products. Being able to compare with other brands may be important for market research teams to adjust shades of products to align with future marketing strategies. 

2. What are the shades of foundation sold in a specific area/country in terms of range and skin tones? 

The range and skin tones of the best-selling foundations in a particular area/country may be useful for marketing research teams when they are interested in expanding business to this area/country. 

3. What are the available brands and shades in a particular area/country? 

This could be helpful for women in choosing foundation. The dashboard will allow the audience to customize the shade of interest, and return similar shades offered by each brand. 

Hope these ideas help with brainstorming!

**Comment by rainbowxyt0305** [comment]
I really like all your ideas Elina! They are very insightful and well thought out! To add on that, I am thinking maybe we could have a more general/broad overarching research question like: 

`What are the different shades of foundations available for each group, for each brand, and for each product?`

Then, we could incorporate both Lu and Elina's ideas into individual plotting.

**Comment by elabandari** [comment]
Hi all, 

Thanks for contributing to this lively discussion. I agree with Rachel's suggestion of having an overarching question of `What are the different shades of foundations available for each group, for each brand, and for each product?`, however, since there are many products I suggest narrowing the question down to `What are the different shades of foundations available in each of the global best-seller groups and within each brand?`. 

I really like all of the suggestions made and can see quite a bit of overlap. 

I really like @KangboLu first suggestion  `X = group, Y = shades for studying what are shades available from each group's best-seller product lists. The choice of the chart can be a 2D heatmap.` as I think this is the most naturally arising question from the dataset. It also captures @elina-linglin second research question. 

Again I also really like @KangboLu number 2&3 suggestions and they collectively capture/answer @elina-linglin number 1&3 research question.

I think it's easy to bring them all together under a cohesive research thread. I feel given these research question the most natural target audience may be a global makeup marketing and consulting company. Our dashboard would give them the information such company would need to counsel makeup companies on the shades they need in their upcoming collections and how to cater the shade range for different countries across the globe.
